name: first workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hellow world!"
      - name: Pring goodbye
        run: echo "done - Bye!"
